// Mock data shaped to /context/api-contracts and /context/model
window.FLETER_DATA = {
  user: {
    nombre: "Mariana",
    apellido: "Vázquez",
    email: "mariana@distribucionlumina.com.ar",
    nombre_empresa: "Distribuidora Lumina",
    cuit: "30-71445098-3",
    rol: "CLIENTE",
  },
  periodo: {
    label: "Abril 2026",
    desde: "2026-04-01",
    hasta: "2026-04-30",
  },
  resumen: {
    total_gastado: 1842350,
    cantidad_viajes: 47,
    costo_promedio: 39198,
    viaje_mas_caro: { id: "VJ-2419", monto: 184500, ruta: "Vicente López → Pilar" },
    viaje_mas_barato: { id: "VJ-2387", monto: 8400, ruta: "Palermo → Belgrano" },
    por_zona: { CABA: 612400, PROVINCIA: 894200, MIXTO: 335750 },
    alertas_recibidas: 4,
    destinos_frecuentes: [
      { direccion: "Av. Crovara 4250, La Tablada", cantidad: 11, zona: "PROVINCIA" },
      { direccion: "Mercado Central, Tapiales", cantidad: 8, zona: "PROVINCIA" },
      { direccion: "Dock Sud, Avellaneda", cantidad: 6, zona: "PROVINCIA" },
      { direccion: "Av. Warnes 1840, CABA", cantidad: 5, zona: "CABA" },
      { direccion: "Parque Industrial Pilar", cantidad: 4, zona: "MIXTO" },
    ],
    // weekly bar series
    fletes_por_semana: [
      { semana: "Sem 1", viajes: 9, gasto: 312400 },
      { semana: "Sem 2", viajes: 14, gasto: 521800 },
      { semana: "Sem 3", viajes: 11, gasto: 408200 },
      { semana: "Sem 4", viajes: 13, gasto: 599950 },
    ],
  },
  viajes: [
    {
      id: "VJ-2419",
      fecha: "2026-04-26T08:30:00",
      origen: "Av. Warnes 1840, CABA",
      destino: "Parque Industrial Pilar — Lote 14",
      tipo_zona: "MIXTO",
      estado: "ENTREGADO",
      precio_estimado: 162000,
      precio_final: 184500,
      duracion_estimada: 95,
      duracion_real: 138,
      km_reales: 71,
      alertas_count: 2,
      conductor: { nombre: "Hernán Pereyra", calificacion: 4.8, telefono: "+54 11 5544 8821" },
      ayudante: { nombre: "Lautaro Méndez", rol: "Carga y descarga" },
      vehiculo: {
        patente: "AE 410 NX",
        tipo: "Camión 8m³",
        condiciones: ["VOLUMINOSO", "CARGA_PESADA"],
        credenciales: ["VTV vigente", "Seguro AllRisk", "RUTA habilitado"],
      },
      carga: { descripcion: "12 pallets de luminarias LED industriales", peso_kg: 1840 },
      paradas: [
        { orden: 1, direccion: "Av. Warnes 1840, CABA", estado: "ENTREGADO", hora: "08:42" },
        { orden: 2, direccion: "Depósito Provisorio, Gral. Paz km 4", estado: "ENTREGADO", hora: "09:55" },
        { orden: 3, direccion: "Parque Industrial Pilar — Lote 14", estado: "ENTREGADO", hora: "10:48" },
      ],
      alertas: [
        { tipo: "DESVIO", descripcion: "Desvío de 3.2 km respecto a ruta óptima", timestamp: "09:14" },
        { tipo: "PARADA_SOSPECHOSA", descripcion: "Detención de 18 min sin parada planificada", timestamp: "09:31" },
      ],
      transacciones: [
        { tipo: "COBRO_INICIAL", monto: 162000, fecha: "08:30" },
        { tipo: "AJUSTE", monto: 22500, fecha: "11:02", motivo: "Tiempo extra + km adicionales" },
      ],
    },
    {
      id: "VJ-2418",
      fecha: "2026-04-25T14:10:00",
      origen: "Depósito Lumina — Villa Crespo",
      destino: "Av. Crovara 4250, La Tablada",
      tipo_zona: "PROVINCIA",
      estado: "ENTREGADO",
      precio_final: 47800,
      precio_estimado: 47800,
      duracion_estimada: 55,
      duracion_real: 52,
      km_reales: 24,
      alertas_count: 0,
      conductor: { nombre: "Sofía Albanese", calificacion: 4.9 },
      vehiculo: { patente: "AC 882 LP", tipo: "Utilitario 4m³", condiciones: [], credenciales: ["VTV vigente"] },
      carga: { descripcion: "6 pallets — repuestos eléctricos", peso_kg: 540 },
      paradas: [
        { orden: 1, direccion: "Depósito Lumina — Villa Crespo", estado: "ENTREGADO", hora: "14:18" },
        { orden: 2, direccion: "Av. Crovara 4250, La Tablada", estado: "ENTREGADO", hora: "15:10" },
      ],
      alertas: [],
    },
    {
      id: "VJ-2417",
      fecha: "2026-04-25T09:00:00",
      origen: "Palermo — Honduras 5400",
      destino: "Belgrano — Cabildo 2900",
      tipo_zona: "CABA",
      estado: "ENTREGADO",
      precio_final: 8400,
      duracion_real: 28,
      km_reales: 6.4,
      alertas_count: 0,
      conductor: { nombre: "Diego Roldán", calificacion: 4.6 },
      vehiculo: { patente: "AB 091 KQ", tipo: "Moto-flete", condiciones: [], credenciales: ["VTV vigente"] },
      carga: { descripcion: "2 cajas — muestras comerciales", peso_kg: 18 },
      paradas: [],
      alertas: [],
    },
    {
      id: "VJ-2416",
      fecha: "2026-04-24T11:45:00",
      origen: "Mercado Central, Tapiales",
      destino: "Local Lumina — Caballito",
      tipo_zona: "MIXTO",
      estado: "ENTREGADO",
      precio_final: 32400,
      duracion_real: 71,
      km_reales: 22,
      alertas_count: 1,
      conductor: { nombre: "Paula Ríos", calificacion: 4.7 },
      vehiculo: { patente: "AD 552 NM", tipo: "Camión 6m³", condiciones: ["VOLUMINOSO"] },
      carga: { descripcion: "Mercadería seca — 1100 kg", peso_kg: 1100 },
      alertas: [{ tipo: "DESVIO", descripcion: "Desvío de 1.8 km", timestamp: "12:21" }],
    },
    {
      id: "VJ-2415",
      fecha: "2026-04-24T08:00:00",
      origen: "Dock Sud, Avellaneda",
      destino: "Depósito Lumina — Villa Crespo",
      tipo_zona: "PROVINCIA",
      estado: "ENTREGADO",
      precio_final: 64200,
      duracion_real: 92,
      km_reales: 31,
      alertas_count: 0,
      conductor: { nombre: "Hernán Pereyra", calificacion: 4.8 },
      vehiculo: { patente: "AE 410 NX", tipo: "Camión 8m³", condiciones: ["CARGA_PESADA"] },
      carga: { descripcion: "Contenedor parcial — insumos importados", peso_kg: 2200 },
      alertas: [],
    },
    {
      id: "VJ-2414",
      fecha: "2026-04-23T16:20:00",
      origen: "Av. Warnes 1840, CABA",
      destino: "Av. Crovara 4250, La Tablada",
      tipo_zona: "MIXTO",
      estado: "ENTREGADO",
      precio_final: 41800,
      duracion_real: 64,
      km_reales: 19,
      alertas_count: 0,
      conductor: { nombre: "Sofía Albanese", calificacion: 4.9 },
      vehiculo: { patente: "AC 882 LP", tipo: "Utilitario 4m³" },
      alertas: [],
    },
    {
      id: "VJ-2413",
      fecha: "2026-04-23T10:00:00",
      origen: "Depósito Lumina — Villa Crespo",
      destino: "Mercado Central, Tapiales",
      tipo_zona: "MIXTO",
      estado: "CANCELADO",
      precio_final: 0,
      duracion_real: 0,
      km_reales: 0,
      alertas_count: 0,
      alertas: [],
    },
    {
      id: "VJ-2412",
      fecha: "2026-04-22T13:00:00",
      origen: "Local Lumina — Caballito",
      destino: "Av. Crovara 4250, La Tablada",
      tipo_zona: "PROVINCIA",
      estado: "ENTREGADO",
      precio_final: 38900,
      duracion_real: 68,
      km_reales: 21,
      alertas_count: 0,
      conductor: { nombre: "Paula Ríos", calificacion: 4.7 },
      vehiculo: { patente: "AD 552 NM", tipo: "Camión 6m³" },
      alertas: [],
    },
    {
      id: "VJ-2411",
      fecha: "2026-04-22T08:30:00",
      origen: "Palermo — Honduras 5400",
      destino: "Recoleta — Las Heras 2200",
      tipo_zona: "CABA",
      estado: "ENTREGADO",
      precio_final: 11200,
      duracion_real: 24,
      km_reales: 4.8,
      alertas_count: 0,
      conductor: { nombre: "Diego Roldán", calificacion: 4.6 },
      vehiculo: { patente: "AB 091 KQ", tipo: "Moto-flete" },
      alertas: [],
    },
    {
      id: "VJ-2410",
      fecha: "2026-04-21T15:00:00",
      origen: "Depósito Lumina — Villa Crespo",
      destino: "Parque Industrial Pilar",
      tipo_zona: "MIXTO",
      estado: "ENTREGADO",
      precio_final: 96400,
      duracion_real: 124,
      km_reales: 58,
      alertas_count: 1,
      conductor: { nombre: "Hernán Pereyra", calificacion: 4.8 },
      vehiculo: { patente: "AE 410 NX", tipo: "Camión 8m³" },
      alertas: [{ tipo: "PARADA_SOSPECHOSA", descripcion: "Detención de 12 min en zona no planificada", timestamp: "16:18" }],
    },
    {
      id: "VJ-2409",
      fecha: "2026-04-21T09:30:00",
      origen: "Av. Warnes 1840, CABA",
      destino: "Belgrano — Cabildo 2900",
      tipo_zona: "CABA",
      estado: "ENTREGADO",
      precio_final: 14800,
      duracion_real: 32,
      km_reales: 7.2,
      alertas_count: 0,
      conductor: { nombre: "Diego Roldán", calificacion: 4.6 },
      vehiculo: { patente: "AB 091 KQ", tipo: "Moto-flete" },
      alertas: [],
    },
  ],
};
